version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5433:5432"  

  airflow-init:
    image: apache/airflow:2.8.1-python3.10
    container_name: airflow_init
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
    command: >
      bash -c "
      pip install psycopg2-binary python-dotenv requests &&
      airflow db init &&
      airflow users create --username airflow --password airflow --firstname Air --lastname Flow --role Admin --email admin@example.com
      "

  airflow-webserver:
    image: apache/airflow:2.8.1-python3.10
    container_name: airflow_webserver
    restart: always
    depends_on:
      - postgres
      - airflow-init
    ports:
      - "8080:8080"
    environment:
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
    volumes:
      - ./dags:/opt/airflow/dags
      - ./src:/opt/airflow/src
      - ./logs:/opt/airflow/logs
      - ./.env.docker:/opt/airflow/.env
    command: >
      bash -c "
      pip install psycopg2-binary python-dotenv requests &&
      airflow webserver
      "

  airflow-scheduler:
    image: apache/airflow:2.8.1-python3.10
    container_name: airflow_scheduler
    restart: always
    depends_on:
      - postgres
      - airflow-init
    environment:
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__WEBSERVER__SECRET_KEY: my_secret_key_123
    volumes:
      - ./dags:/opt/airflow/dags
      - ./src:/opt/airflow/src
      - ./logs:/opt/airflow/logs
      - ./.env.docker:/opt/airflow/.env
    command: >
      bash -c "
      pip install psycopg2-binary python-dotenv requests &&
      airflow scheduler
      "